on: push

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.OVH_SERVER }}
          username: ${{ secrets.OVH_USERNAME }}
          password: ${{ secrets.OVH_PASSWORD }}
          server-dir: /www/
